version: '3.11'
services:
  python3:
    restart: always
    build: .
    command: flask run --host=0.0.0.0 --reload
    container_name: 'python3'
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development